### ISSUE TITLE
[Enchancement] VoiceActivityShow

### ISSUE THREAD

**Issue by Soulivan71** [Neodymium7/BetterDiscordStuff#16]
**Is your feature request related to a problem? Please describe.**

See it in profile user

**Describe the solution you'd like**
See picture

**Additional context**
![image](https://user-images.githubusercontent.com/36502190/178389507-15f92ad1-ebd8-4132-9f0e-9c58f2ae3cb4.png)
Here its the only space that isn't displayed

**Comment by Neodymium7** [comment]
I added this in the latest update (v1.3.0). VoiceActivity info will be in the "Activity" tab.

**Comment by Soulivan71** [comment]
Yeah but we need to do one click more 😭

**Comment by Neodymium7** [comment]
In my opinion, just placing the info directly in the middle of the modal would be out of place, and the activity tab is the one that best fits what the info is. The modal is not really meant for finding things quickly, that's more the purpose of the user popout, where no extra clicks are required to find things like activities and bios. If the extra click is too much of an inconvenience, I can add an option to put the voice info right on the modal instead of in a tab.
