### ISSUE TITLE
[Enchancement]VoiceActivity.plugin.

### ISSUE THREAD

**Issue by DogancanYr** [Neodymium7/BetterDiscordStuff#59]
Is it possible to increase the volume by more than 200%?

**Comment by Neodymium7** [comment]
No, this is not a feature of VoiceActivity, and not something I plan to add, since it is unrelated to the main functionality of the plugin.

A quick search on the BetterDiscord website yielded me [BetterVolume](https://betterdiscord.app/plugin/BetterVolume), which may do what you’re asking for if I’m understanding your request correctly.

**Comment by DogancanYr** [comment]
> No, this is not a feature of VoiceActivity, and not something I plan to add, since it is unrelated to the main functionality of the plugin.
> 
> A quick search on the BetterDiscord website yielded me [BetterVolume](https://betterdiscord.app/plugin/BetterVolume), which may do what you’re asking for if I’m understanding your request correctly.

I wrote it for that plugin but I messed it up.
